server:
  port: 8762

spring:
  application:
    name: service-hi
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1
        min-idle: 0
    timeout: 500
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://122.51.19.164:8761/eureka/


