spring:
  datasource:
    url: jdbc:mysql://122.51.19.164:3306/recommend?serverTimezone=GMT
    username: root
    password: Comfortalway1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-recommend

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
